#!/bin/bash
# Quick Guide: How to Update Role Templates
# This shows you how to add/remove permissions from role templates

echo "🎨 UPDATING ROLE TEMPLATES - QUICK GUIDE"
echo ""
echo "================================================"
echo "OPTION 1: Through the UI (Recommended)"
echo "================================================"
echo ""
echo "1. Login as Super Admin"
echo "2. Go to Settings → Roles"
echo "3. You'll see ALL roles including System templates"
echo "4. Find the role template (e.g., 'Production Manager')"
echo "5. Click Edit"
echo "6. Add/remove permissions"
echo "7. Save"
echo ""
echo "⚠️  Changes only affect NEW clients!"
echo "💡 To update existing clients, use Option 2"
echo ""
echo "================================================"
echo "OPTION 2: Through Terminal (For Existing Clients)"
echo "================================================"
echo ""
echo "Example: Add settings permission to Production Manager"
echo ""
echo "npx tsx -e '"
echo "import { PrismaClient } from \"@prisma/client\";"
echo "const prisma = new PrismaClient();"
echo "(async () => {"
echo "  // 1. Get System client"
echo "  const systemClient = await prisma.client.findUnique({ "
echo "    where: { slug: \"system\" } "
echo "  });"
echo ""
echo "  // 2. Find the role template"
echo "  const role = await prisma.role.findFirst({ "
echo "    where: { "
echo "      clientId: systemClient.id, "
echo "      name: \"Production Manager\" "
echo "    } "
echo "  });"
echo ""
echo "  // 3. Find the permission you want to add"
echo "  const permission = await prisma.permission.findFirst({ "
echo "    where: { "
echo "      resource: \"settings\", "
echo "      action: \"view\" "
echo "    } "
echo "  });"
echo ""
echo "  // 4. Add permission to template"
echo "  await prisma.rolePermission.create({ "
echo "    data: { "
echo "      roleId: role.id, "
echo "      permissionId: permission.id "
echo "    } "
echo "  });"
echo ""
echo "  console.log(\"✅ Template updated!\");"
echo "  await prisma.\$disconnect();"
echo "})();'"
echo ""
echo "================================================"
echo "AVAILABLE ROLE TEMPLATES"
echo "================================================"
echo ""
echo "1. Admin (33 permissions)"
echo "   - Full access to all bakery operations"
echo ""
echo "2. Sales Manager (14 permissions)"
echo "   - Customers, orders, view inventory"
echo ""
echo "3. Inventory Manager (12 permissions)"
echo "   - Inventory management, view production"
echo ""
echo "4. Production Manager (14 permissions)"
echo "   - Production, recipes, view inventory, settings"
echo ""
echo "================================================"
echo "AVAILABLE RESOURCES & ACTIONS"
echo "================================================"
echo ""
echo "Resources:"
echo "  - dashboard, raw-materials, finished-products"
echo "  - recipes, production, customers, customer-orders"
echo "  - settings, users, roles, clients, permissions"
echo "  - reports, api-test"
echo ""
echo "Actions:"
echo "  - view, create, edit, delete"
echo ""
echo "================================================"
echo "TO UPDATE EXISTING CLIENTS"
echo "================================================"
echo ""
echo "Run the sync script:"
echo "npx tsx backend/scripts/sync-clients-with-templates.ts"
echo ""
echo "Or use the terminal command to update specific role in all clients"
echo ""
