import React, { useState } from 'react';
import {
  Container,
  Typography,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  Button,
  Box,
  Chip,
  TextField,
  InputAdornment,
  Alert,
  CircularProgress,
  IconButton,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Grid,
} from '@mui/material';
import {
  Search as SearchIcon,
  Download as DownloadIcon,
  Refresh as RefreshIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  Label as LabelIcon,
  Info as InfoIcon,
  CheckCircle as CheckIcon,
} from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { skuReferencesApi, categoriesApi, storageLocationsApi, unitsApi } from '../services/realApi';
import { SkuReference, CreateSkuReferenceData } from '../types';

const SkuReferencePage: React.FC = () => {
  const queryClient = useQueryClient();

  // State
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(25);
  const [searchTerm, setSearchTerm] = useState('');
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [usageDialogOpen, setUsageDialogOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<SkuReference | null>(null);
  const [deletingItem, setDeletingItem] = useState<SkuReference | null>(null);
  const [usageData, setUsageData] = useState<any>(null);
  const [formData, setFormData] = useState<CreateSkuReferenceData>({
    name: '',
    sku: '',
    description: '',
    unit: '',
    unitPrice: undefined,
    reorderLevel: undefined,
    categoryId: '',
    storageLocationId: '',
  });
  const [error, setError] = useState<string>('');
  const [autoGeneratedSku, setAutoGeneratedSku] = useState(false);

  // Fetch data
  const { data: skuReferences = [], isLoading, refetch } = useQuery<SkuReference[]>({
    queryKey: ['sku-references', searchTerm],
    queryFn: async () => {
      const response = await skuReferencesApi.getAll({ search: searchTerm });
      return response.data || [];
    },
  });

  const { data: categories = [] } = useQuery({
    queryKey: ['categories'],
    queryFn: async () => {
      const response = await categoriesApi.getAll();
      return response.data || [];
    },
  });

  const { data: storageLocations = [] } = useQuery({
    queryKey: ['storage-locations'],
    queryFn: async () => {
      const response = await storageLocationsApi.getAll();
      return response.data || [];
    },
  });

  const { data: unitsResponse } = useQuery({
    queryKey: ['units'],
    queryFn: unitsApi.getAll,
  });
  const units = unitsResponse?.data || [];

  // Mutations
  const createMutation = useMutation({
    mutationFn: (data: CreateSkuReferenceData) => skuReferencesApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sku-references'] });
      handleCloseDialog();
      setError('');
    },
    onError: (error: any) => {
      setError(error.response?.data?.error || error.message || 'Failed to create SKU reference');
    },
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: CreateSkuReferenceData }) =>
      skuReferencesApi.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sku-references'] });
      handleCloseDialog();
      setError('');
    },
    onError: (error: any) => {
      setError(error.response?.data?.error || error.message || 'Failed to update SKU reference');
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => skuReferencesApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sku-references'] });
      setDeleteDialogOpen(false);
      setDeletingItem(null);
      setError('');
    },
    onError: (error: any) => {
      setError(error.response?.data?.error || error.message || 'Failed to delete SKU reference');
    },
  });

  // Handlers
  const handleOpenDialog = (item?: SkuReference) => {
    if (item) {
      setEditingItem(item);
      setFormData({
        name: item.name,
        sku: item.sku,
        description: item.description || '',
        unit: item.unit || '',
        unitPrice: item.unitPrice,
        reorderLevel: item.reorderLevel,
        categoryId: item.categoryId || '',
        storageLocationId: item.storageLocationId || '',
      });
      setAutoGeneratedSku(false);
    } else {
      setEditingItem(null);
      setFormData({
        name: '',
        sku: '',
        description: '',
        unit: '',
        unitPrice: undefined,
        reorderLevel: undefined,
        categoryId: '',
        storageLocationId: '',
      });
      setAutoGeneratedSku(false);
    }
    setError('');
    setDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setDialogOpen(false);
    setEditingItem(null);
    setError('');
    setAutoGeneratedSku(false);
  };

  const handleSubmit = () => {
    if (!formData.name.trim()) {
      setError('Name is required');
      return;
    }

    if (!formData.sku || !formData.sku.trim()) {
      setError('SKU is required');
      return;
    }

    const submitData = {
      ...formData,
      description: formData.description || undefined,
      unit: formData.unit || undefined,
      categoryId: formData.categoryId || undefined,
      storageLocationId: formData.storageLocationId || undefined,
    };

    if (editingItem) {
      updateMutation.mutate({ id: editingItem.id, data: submitData });
    } else {
      createMutation.mutate(submitData);
    }
  };

  const handleDeleteClick = (item: SkuReference) => {
    setDeletingItem(item);
    setDeleteDialogOpen(true);
    setError('');
  };

  const handleDeleteConfirm = () => {
    if (deletingItem) {
      deleteMutation.mutate(deletingItem.id);
    }
  };

  const handleCheckUsage = async (item: SkuReference) => {
    try {
      const response = await skuReferencesApi.checkUsage(item.id);
      setUsageData(response.data);
      setUsageDialogOpen(true);
    } catch (error: any) {
      setError(error.response?.data?.error || 'Failed to fetch usage data');
    }
  };

  const handleExport = () => {
    const headers = [
      'Name',
      'SKU',
      'Description',
      'Unit Price',
      'Unit',
      'Reorder Level',
      'Category',
      'Storage Location',
      'Raw Materials',
      'Finished Products',
    ];
    const rows = skuReferences.map((item) => [
      item.name,
      item.sku,
      item.description || '',
      item.unitPrice?.toString() || '',
      item.unit || '',
      item.reorderLevel?.toString() || '',
      item.category?.name || '',
      item.storageLocation?.name || '',
      item._count?.rawMaterials?.toString() || '0',
      item._count?.finishedProducts?.toString() || '0',
    ]);
    const csv = [
      headers.join(','),
      ...rows.map((row) => row.map((cell) => `"${cell}"`).join(',')),
    ].join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sku-references-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Filtered data
  const filteredData = skuReferences;

  return (
    <Container maxWidth="xl" sx={{ py: 4 }}>
      {/* Header */}
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Box display="flex" alignItems="center" gap={1}>
          <LabelIcon sx={{ fontSize: 32, color: 'primary.main' }} />
          <Typography variant="h4" fontWeight="bold">
            SKU Reference Templates
          </Typography>
        </Box>
        <Box display="flex" gap={1}>
          <Tooltip title="Refresh">
            <IconButton color="primary" onClick={() => refetch()}>
              <RefreshIcon />
            </IconButton>
          </Tooltip>
          <Button
            variant="outlined"
            startIcon={<DownloadIcon />}
            onClick={handleExport}
            disabled={filteredData.length === 0}
          >
            Export CSV
          </Button>
          <Button variant="contained" startIcon={<AddIcon />} onClick={() => handleOpenDialog()}>
            New SKU Reference
          </Button>
        </Box>
      </Box>

      {/* Info Alert */}
      <Alert severity="info" sx={{ mb: 3 }}>
        SKU Reference Templates serve as master data for creating raw materials and finished products.
        Define default values once and reuse them across your inventory.
      </Alert>

      {/* Error Alert */}
      {error && (
        <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>
          {error}
        </Alert>
      )}

      {/* Search and Table */}
      <Paper sx={{ width: '100%', mb: 2 }}>
        <Box p={2} pb={0}>
          <TextField
            fullWidth
            placeholder="Search by name, SKU, or description..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon />
                </InputAdornment>
              ),
            }}
          />
        </Box>

        {isLoading ? (
          <Box display="flex" justifyContent="center" alignItems="center" p={8}>
            <CircularProgress />
          </Box>
        ) : (
          <>
            <TableContainer>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 'bold' }}>Name</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>SKU</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Category</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Unit Price</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Unit</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Storage</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Usage</TableCell>
                    <TableCell align="right" sx={{ fontWeight: 'bold' }}>
                      Actions
                    </TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {filteredData
                    .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                    .map((item) => {
                      const totalUsage =
                        (item._count?.rawMaterials || 0) + (item._count?.finishedProducts || 0);
                      return (
                        <TableRow key={item.id} hover>
                          <TableCell>
                            <Typography variant="body2" fontWeight="medium">
                              {item.name}
                            </Typography>
                            {item.description && (
                              <Typography variant="caption" color="text.secondary">
                                {item.description}
                              </Typography>
                            )}
                          </TableCell>
                          <TableCell>
                            <Typography
                              variant="body2"
                              fontFamily="monospace"
                              sx={{
                                backgroundColor: '#f5f5f5',
                                px: 1,
                                py: 0.5,
                                borderRadius: 1,
                                display: 'inline-block',
                              }}
                            >
                              {item.sku}
                            </Typography>
                          </TableCell>
                          <TableCell>
                            {item.category ? (
                              <Chip label={item.category.name} size="small" />
                            ) : (
                              <Typography variant="body2" color="text.secondary">
                                —
                              </Typography>
                            )}
                          </TableCell>
                          <TableCell>
                            {item.unitPrice ? `$${item.unitPrice.toFixed(2)}` : '—'}
                          </TableCell>
                          <TableCell>{item.unit || '—'}</TableCell>
                          <TableCell>
                            {item.storageLocation ? item.storageLocation.name : '—'}
                          </TableCell>
                          <TableCell>
                            <Tooltip title="Click for details">
                              <Chip
                                label={totalUsage}
                                size="small"
                                color={totalUsage > 0 ? 'primary' : 'default'}
                                onClick={() => handleCheckUsage(item)}
                                sx={{ cursor: 'pointer' }}
                              />
                            </Tooltip>
                          </TableCell>
                          <TableCell align="right">
                            <Tooltip title="View Usage">
                              <IconButton
                                size="small"
                                onClick={() => handleCheckUsage(item)}
                                color="info"
                              >
                                <InfoIcon fontSize="small" />
                              </IconButton>
                            </Tooltip>
                            <Tooltip title="Edit">
                              <IconButton
                                size="small"
                                onClick={() => handleOpenDialog(item)}
                                color="primary"
                              >
                                <EditIcon fontSize="small" />
                              </IconButton>
                            </Tooltip>
                            <Tooltip title={totalUsage > 0 ? 'In use - cannot delete' : 'Delete'}>
                              <span>
                                <IconButton
                                  size="small"
                                  onClick={() => handleDeleteClick(item)}
                                  color="error"
                                  disabled={totalUsage > 0}
                                >
                                  <DeleteIcon fontSize="small" />
                                </IconButton>
                              </span>
                            </Tooltip>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  {filteredData.length === 0 && (
                    <TableRow>
                      <TableCell colSpan={8} align="center" sx={{ py: 8 }}>
                        <Typography variant="body1" color="text.secondary">
                          {searchTerm
                            ? 'No matching SKU references found'
                            : 'No SKU references yet. Create one to get started!'}
                        </Typography>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </TableContainer>
            <TablePagination
              rowsPerPageOptions={[10, 25, 50, 100]}
              component="div"
              count={filteredData.length}
              rowsPerPage={rowsPerPage}
              page={page}
              onPageChange={(_e, newPage) => setPage(newPage)}
              onRowsPerPageChange={(e) => {
                setRowsPerPage(parseInt(e.target.value, 10));
                setPage(0);
              }}
            />
          </>
        )}
      </Paper>

      {/* Create/Edit Dialog */}
      <Dialog open={dialogOpen} onClose={handleCloseDialog} maxWidth="md" fullWidth>
        <DialogTitle>{editingItem ? 'Edit SKU Reference' : 'New SKU Reference'}</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Name *"
                value={formData.name}
                onChange={(e) => {
                  const newName = e.target.value;
                  setFormData({ ...formData, name: newName });

                  // Auto-generate SKU from name when creating (not editing)
                  if (!editingItem && newName) {
                    const cleanName = newName
                      .trim()
                      .toUpperCase()
                      .replace(/[^A-Z0-9]+/g, '-')
                      .replace(/^-+|-+$/g, '');
                    setFormData((prev) => ({ ...prev, sku: cleanName }));
                    setAutoGeneratedSku(true);
                  }
                }}
                helperText="Product or material name"
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="SKU *"
                value={formData.sku}
                onChange={(e) => {
                  setFormData({ ...formData, sku: e.target.value });
                  setAutoGeneratedSku(false);
                }}
                helperText={
                  autoGeneratedSku
                    ? 'Auto-generated from name'
                    : 'Editable – unique identifier for this template'
                }
                InputProps={{
                  endAdornment: autoGeneratedSku ? (
                    <Chip size="small" label="Auto" icon={<CheckIcon />} color="primary" />
                  ) : null,
                }}
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Description"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                multiline
                rows={2}
              />
            </Grid>
            <Grid item xs={6}>
              <TextField
                fullWidth
                label="Unit Price"
                type="number"
                value={formData.unitPrice || ''}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    unitPrice: e.target.value ? parseFloat(e.target.value) : undefined,
                  })
                }
                InputProps={{ startAdornment: <InputAdornment position="start">$</InputAdornment> }}
              />
            </Grid>
            <Grid item xs={6}>
              <FormControl fullWidth>
                <InputLabel>Unit</InputLabel>
                <Select
                  value={formData.unit}
                  label="Unit"
                  onChange={(e) => setFormData({ ...formData, unit: e.target.value })}
                >
                  <MenuItem value="">
                    <em>None</em>
                  </MenuItem>
                  {Array.isArray(units) && units
                    .filter((u) => u.isActive)
                    .sort((a, b) => {
                      // Group by category, then sort by name
                      if (a.category !== b.category) {
                        return a.category.localeCompare(b.category);
                      }
                      return a.name.localeCompare(b.name);
                    })
                    .map((unit) => (
                      <MenuItem key={unit.id} value={unit.symbol}>
                        {unit.symbol} - {unit.name} ({unit.category})
                      </MenuItem>
                    ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={6}>
              <TextField
                fullWidth
                label="Reorder Level"
                type="number"
                value={formData.reorderLevel || ''}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    reorderLevel: e.target.value ? parseFloat(e.target.value) : undefined,
                  })
                }
              />
            </Grid>
            <Grid item xs={6}>
              <FormControl fullWidth>
                <InputLabel>Category</InputLabel>
                <Select
                  value={formData.categoryId}
                  label="Category"
                  onChange={(e) => setFormData({ ...formData, categoryId: e.target.value })}
                >
                  <MenuItem value="">
                    <em>None</em>
                  </MenuItem>
                  {Array.isArray(categories) && categories.map((cat) => (
                    <MenuItem key={cat.id} value={cat.id}>
                      {cat.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12}>
              <FormControl fullWidth>
                <InputLabel>Storage Location</InputLabel>
                <Select
                  value={formData.storageLocationId}
                  label="Storage Location"
                  onChange={(e) =>
                    setFormData({ ...formData, storageLocationId: e.target.value })
                  }
                >
                  <MenuItem value="">
                    <em>None</em>
                  </MenuItem>
                  {Array.isArray(storageLocations) && storageLocations.map((loc) => (
                    <MenuItem key={loc.id} value={loc.id}>
                      {loc.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>Cancel</Button>
          <Button
            onClick={handleSubmit}
            variant="contained"
            disabled={createMutation.isPending || updateMutation.isPending}
          >
            {editingItem ? 'Update' : 'Create'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialogOpen} onClose={() => setDeleteDialogOpen(false)}>
        <DialogTitle>Confirm Delete</DialogTitle>
        <DialogContent>
          <Typography>
            Are you sure you want to delete the SKU reference "<strong>{deletingItem?.name}</strong>
            "?
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
            This action cannot be undone.
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeleteDialogOpen(false)}>Cancel</Button>
          <Button
            onClick={handleDeleteConfirm}
            variant="contained"
            color="error"
            disabled={deleteMutation.isPending}
          >
            Delete
          </Button>
        </DialogActions>
      </Dialog>

      {/* Usage Details Dialog */}
      <Dialog
        open={usageDialogOpen}
        onClose={() => setUsageDialogOpen(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>SKU Reference Usage</DialogTitle>
        <DialogContent>
          {usageData && (
            <>
              <Typography variant="h6" gutterBottom>
                {usageData.skuReference.name} ({usageData.skuReference.sku})
              </Typography>
              <Typography variant="body2" color="text.secondary" gutterBottom>
                Total Usage: {usageData.usage.totalCount} items
              </Typography>

              {usageData.usage.rawMaterials.length > 0 && (
                <Box sx={{ mt: 2 }}>
                  <Typography variant="subtitle2" fontWeight="bold">
                    Raw Materials ({usageData.usage.rawMaterials.length})
                  </Typography>
                  {usageData.usage.rawMaterials.map((item: any) => (
                    <Typography key={item.id} variant="body2">
                      • {item.name} - {item.batchNumber} ({item.quantity} {item.unit})
                    </Typography>
                  ))}
                </Box>
              )}

              {usageData.usage.finishedProducts.length > 0 && (
                <Box sx={{ mt: 2 }}>
                  <Typography variant="subtitle2" fontWeight="bold">
                    Finished Products ({usageData.usage.finishedProducts.length})
                  </Typography>
                  {usageData.usage.finishedProducts.map((item: any) => (
                    <Typography key={item.id} variant="body2">
                      • {item.name} - {item.batchNumber} ({item.quantity} {item.unit})
                    </Typography>
                  ))}
                </Box>
              )}

              {usageData.usage.totalCount === 0 && (
                <Alert severity="info" sx={{ mt: 2 }}>
                  This SKU reference is not currently in use.
                </Alert>
              )}
            </>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setUsageDialogOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>
    </Container>
  );
};

export default SkuReferencePage;
