import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import {
  Container,
  Typography,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  Button,
  Box,
  Chip,
  TextField,
  InputAdornment,
  Alert,
  CircularProgress,
  IconButton,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Grid,
  useTheme,
  useMediaQuery,
  Card,
  CardContent,
  CardActions,
  CardHeader,
  Avatar,
  Stack,
  Drawer,
  Divider,
  Snackbar,
} from '@mui/material';
import {
  Search as SearchIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  Label as LabelIcon,
  Info as InfoIcon,
  GridView as GridViewIcon,
  ViewList as ListViewIcon,
  Close as CloseIcon,
  FilterList as FilterIcon,
  Inventory as InventoryIcon,
  Category as CategoryIcon,
  CheckCircle as CheckCircleIcon,
} from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { skuReferencesApi, categoriesApi, storageLocationsApi, unitsApi } from '../services/realApi';
import { SkuReference, CreateSkuReferenceData, SkuItemType } from '../types';
import { borderRadius } from '../theme/designTokens';
import { getErrorMessage } from '../utils/api';

const SkuReferencePage: React.FC = () => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
  const location = useLocation();

  const queryClient = useQueryClient();

  // View state
  const [viewMode, setViewMode] = useState<'list' | 'card'>(isMobile ? 'card' : 'list');
  const [filtersOpen, setFiltersOpen] = useState(false);

  // Update viewMode when screen size changes
  useEffect(() => {
    if (isMobile) {
      setViewMode('card');
    }
  }, [isMobile]);

  // State
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(isMobile ? 5 : 10);
  const [searchTerm, setSearchTerm] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('');
  const [storageFilter, setStorageFilter] = useState('');
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [usageDialogOpen, setUsageDialogOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<SkuReference | null>(null);
  const [deletingItem, setDeletingItem] = useState<SkuReference | null>(null);
  const [usageData, setUsageData] = useState<any>(null);
  const [formData, setFormData] = useState<CreateSkuReferenceData>({
    name: '',
    sku: '',
    description: '',
    itemType: SkuItemType.RAW_MATERIAL,
    unit: '',
    unitPrice: undefined,
    reorderLevel: undefined,
    categoryId: '',
    storageLocationId: '',
  });
  const [error, setError] = useState<string>('');
  const [autoGeneratedSku, setAutoGeneratedSku] = useState(false);
  const [snackbar, setSnackbar] = useState<{ open: boolean; message: string; severity: 'success' | 'error' }>({
    open: false,
    message: '',
    severity: 'success',
  });

  // Fetch data
  const { data: skuReferences = [], isLoading } = useQuery<SkuReference[]>({
    queryKey: ['sku-references', searchTerm],
    queryFn: async () => {
      const response = await skuReferencesApi.getAll({ search: searchTerm });
      return response.data || [];
    },
  });

  const { data: categoriesData } = useQuery({
    queryKey: ['categories'],
    queryFn: async () => {
      const response = await categoriesApi.getAll();
      return response.data || [];
    },
  });
  const categories = Array.isArray(categoriesData) ? categoriesData : [];

  const { data: storageLocationsData } = useQuery({
    queryKey: ['storage-locations'],
    queryFn: async () => {
      const response = await storageLocationsApi.getAll();
      return response.data || [];
    },
  });
  const storageLocations = Array.isArray(storageLocationsData) ? storageLocationsData : [];

  const { data: unitsResponse } = useQuery({
    queryKey: ['units'],
    queryFn: unitsApi.getAll,
  });
  const units = unitsResponse?.data || [];

  // Mutations
  const createMutation = useMutation({
    mutationFn: (data: CreateSkuReferenceData) => skuReferencesApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sku-references'] });
      showSnackbar('SKU reference created successfully', 'success');
      handleCloseDialog();
      setError('');
    },
    onError: (error: any) => {
      const errorMessage = getErrorMessage(error);
      setError(errorMessage);
      showSnackbar(errorMessage, 'error');
    },
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: CreateSkuReferenceData }) =>
      skuReferencesApi.update(id, data),
    onSuccess: () => {
      showSnackbar('SKU reference updated successfully', 'success');
      handleCloseDialog();
      queryClient.invalidateQueries({ queryKey: ['sku-references'] });
    },
    onError: (error: any) => {
      const errorMessage = getErrorMessage(error);
      setError(errorMessage);
      showSnackbar(errorMessage, 'error');
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => skuReferencesApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sku-references'] });
      handleCloseDeleteDialog();
      showSnackbar('SKU reference deleted successfully', 'success');
    },
    onError: (error: any) => {
      const errorMessage = getErrorMessage(error);
      showSnackbar(errorMessage, 'error');
    },
  });

  // Handle navigation state to auto-open edit or create dialog
  useEffect(() => {
    // Auto-open edit dialog
    if (location.state?.openEditDialog && location.state?.skuId && skuReferences.length > 0) {
      const skuToEdit = skuReferences.find((sku) => sku.id === location.state.skuId);
      if (skuToEdit) {
        handleOpenDialog(skuToEdit);
        // Clear the state to prevent reopening on subsequent renders
        window.history.replaceState({}, document.title);
      }
    }

    // Auto-open create dialog
    if (location.state?.openCreateDialog) {
      handleOpenDialog(undefined);
      // Clear the state to prevent reopening on subsequent renders
      window.history.replaceState({}, document.title);
    }
  }, [location.state, skuReferences]);

  // Filter data
  const filteredSkuReferences = skuReferences.filter((item) => {
    const matchesSearch = !searchTerm ||
      item.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.sku?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.description?.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesCategory = !categoryFilter || item.categoryId === categoryFilter;
    const matchesStorage = !storageFilter || item.storageLocationId === storageFilter;

    return matchesSearch && matchesCategory && matchesStorage;
  });

  // Calculate KPI data
  const totalCount = skuReferences.length;
  const withCategoryCount = skuReferences.filter(item => item.categoryId).length;
  const withPriceCount = skuReferences.filter(item => item.unitPrice && item.unitPrice > 0).length;

  // Helper functions
  const showSnackbar = (message: string, severity: 'success' | 'error') => {
    setSnackbar({ open: true, message, severity });
  };

  const handleChangePage = (_event: unknown, newPage: number) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  const handleOpenDialog = (item?: SkuReference) => {
    if (item) {
      setEditingItem(item);
      setFormData({
        name: item.name || '',
        sku: item.sku || '',
        description: item.description || '',
        itemType: item.itemType,
        unit: item.unit || '',
        unitPrice: item.unitPrice,
        reorderLevel: item.reorderLevel,
        categoryId: item.categoryId || '',
        storageLocationId: item.storageLocationId || '',
      });
    } else {
      setEditingItem(null);
      setFormData({
        name: '',
        sku: '',
        description: '',
        itemType: SkuItemType.RAW_MATERIAL,
        unit: '',
        unitPrice: undefined,
        reorderLevel: undefined,
        categoryId: '',
        storageLocationId: '',
      });
      setAutoGeneratedSku(true); // Enable auto-generation for new items
    }
    setDialogOpen(true);
    setError('');
  };

  const handleCloseDialog = () => {
    setDialogOpen(false);
    setEditingItem(null);
    setError('');
    setAutoGeneratedSku(false);
    setFormData({
      name: '',
      sku: '',
      description: '',
      itemType: SkuItemType.RAW_MATERIAL,
      unit: '',
      unitPrice: undefined,
      reorderLevel: undefined,
      categoryId: '',
      storageLocationId: '',
    });
  };

  const handleOpenDeleteDialog = (item: SkuReference) => {
    setDeletingItem(item);
    setDeleteDialogOpen(true);
  };

  const handleCloseDeleteDialog = () => {
    setDeleteDialogOpen(false);
    setDeletingItem(null);
  };

  const handleCheckUsage = async (item: SkuReference) => {
    try {
      const response = await skuReferencesApi.checkUsage(item.id);
      setUsageData(response.data);
      setUsageDialogOpen(true);
    } catch (error) {
      showSnackbar('Failed to fetch usage data', 'error');
    }
  };

  /**
   * Generate SKU in industry-standard format: PREFIX-CATEGORY-PRODUCTCODE-SEQUENCE
   * Examples: SKU-DAIRY-MILK-001, SKU-BAKERY-BREAD-023, SKU-GENERAL-FLOUR-042
   */
  const generateSku = (name: string, categoryId?: string): string => {
    const prefix = 'SKU';

    // Get category name for code generation
    let categoryCode = 'GENERAL';
    if (categoryId) {
      const category = categories.find(c => c.id === categoryId);
      if (category) {
        categoryCode = category.name
          .toUpperCase()
          .replace(/[^A-Z0-9]/g, '')
          .substring(0, 6);
      }
    }

    // Generate product code from name (first significant word, 3-5 chars)
    const productCode = name
      .toUpperCase()
      .replace(/[^A-Z0-9\s]/g, '') // Remove special chars
      .split(/\s+/) // Split into words
      .filter(word => word.length > 0) // Remove empty
      .slice(0, 2) // Take first 2 words max
      .join('') // Combine
      .substring(0, 5); // Limit to 5 chars

    // Generate sequence based on current count (will be adjusted by backend)
    const sequence = String(skuReferences.length + 1).padStart(3, '0');

    return `${prefix}-${categoryCode}-${productCode}-${sequence}`;
  };

  const handleNameChange = (name: string) => {
    setFormData(prev => ({ ...prev, name }));

    // Regenerate SKU when name changes (if not editing and SKU was auto-generated)
    if (!editingItem && autoGeneratedSku) {
      const generatedSku = generateSku(name, formData.categoryId);
      setFormData(prev => ({ ...prev, sku: generatedSku }));
    }
  };

  const handleCategoryChange = (categoryId: string) => {
    setFormData(prev => ({ ...prev, categoryId }));

    // Regenerate SKU when category changes (if not editing and SKU was auto-generated)
    if (!editingItem && autoGeneratedSku && formData.name) {
      const generatedSku = generateSku(formData.name, categoryId);
      setFormData(prev => ({ ...prev, sku: generatedSku }));
    }
  };

  const handleSkuChange = (sku: string) => {
    setFormData(prev => ({ ...prev, sku }));
    setAutoGeneratedSku(false);
  };

  const handleNumericChange = (field: 'unitPrice' | 'reorderLevel', value: string) => {
    // Allow empty string, digits, and single decimal point
    if (value === '' || /^\d*\.?\d*$/.test(value)) {
      setFormData(prev => ({
        ...prev,
        [field]: value === '' ? undefined : parseFloat(value) || undefined
      }));
    }
  };

  const handleSubmit = () => {
    if (!formData.name?.trim()) {
      setError('Name is required');
      return;
    }

    if (!formData.sku?.trim()) {
      setError('SKU is required');
      return;
    }

    if (editingItem) {
      updateMutation.mutate({ id: editingItem.id, data: formData });
    } else {
      createMutation.mutate(formData);
    }
  };

  const handleDelete = () => {
    if (deletingItem) {
      deleteMutation.mutate(deletingItem.id);
    }
  };

  if (isLoading) {
    return (
      <Container maxWidth="xl" sx={{ mt: 4, mb: 4 }}>
        <Box display="flex" justifyContent="center" alignItems="center" minHeight="400px">
          <CircularProgress />
        </Box>
      </Container>
    );
  }

  return (
    <Container maxWidth="xl" sx={{ mt: 4, mb: 4 }}>
      {/* Header with responsive design */}
      <Box
        display="flex"
        flexDirection={{ xs: 'column', sm: 'row' }}
        justifyContent="space-between"
        alignItems={{ xs: 'flex-start', sm: 'center' }}
        mb={3}
        gap={2}
      >
        <Box>
          <Typography
            variant={isMobile ? "h4" : "h3"}
            sx={{
              fontWeight: 'bold',
              display: 'flex',
              alignItems: 'center',
              gap: 1,
              mb: 1
            }}
          >
            <LabelIcon sx={{ fontSize: '1.2em', color: 'primary.main' }} />
            SKU Reference
          </Typography>
          <Typography variant="subtitle1" color="text.secondary">
            Manage standardized product identifiers and specifications
          </Typography>
        </Box>

        <Box display="flex" gap={1} width={{ xs: '100%', sm: 'auto' }}>
          {/* View Toggle Buttons */}
          <Box
            sx={{
              display: { xs: 'flex', md: 'flex' },
              border: 1,
              borderColor: 'divider',
              borderRadius: borderRadius.base,
              mr: 1
            }}
          >
            <Tooltip title="List View">
              <IconButton
                color={viewMode === 'list' ? 'primary' : 'default'}
                onClick={() => setViewMode('list')}
                sx={{
                  borderRadius: `${borderRadius.base} 0 0 ${borderRadius.base}`,
                  bgcolor: viewMode === 'list' ? 'action.selected' : 'transparent'
                }}
              >
                <ListViewIcon />
              </IconButton>
            </Tooltip>
            <Tooltip title="Card View">
              <IconButton
                color={viewMode === 'card' ? 'primary' : 'default'}
                onClick={() => setViewMode('card')}
                sx={{
                  borderRadius: `0 ${borderRadius.base} ${borderRadius.base} 0`,
                  bgcolor: viewMode === 'card' ? 'action.selected' : 'transparent'
                }}
              >
                <GridViewIcon />
              </IconButton>
            </Tooltip>
          </Box>

          {/* Add SKU Reference Button */}
          <Button
            variant="contained"
            startIcon={<AddIcon />}
            onClick={() => handleOpenDialog()}
            sx={{
              flexGrow: { xs: 1, sm: 0 },
              whiteSpace: 'nowrap'
            }}
          >
            {!isMobile ? 'Add SKU Reference' : 'Add'}
          </Button>

          {/* Filter Toggle Button for Mobile */}
          {isMobile && (
            <Button
              variant="outlined"
              startIcon={<FilterIcon />}
              onClick={() => setFiltersOpen(!filtersOpen)}
            >
              Filters
            </Button>
          )}
        </Box>
      </Box>

      {/* KPI Cards */}
      <Grid container spacing={1.5} sx={{ mb: 1.5 }}>
        <Grid item xs={12} sm={4} md={4}>
          <Card
            elevation={1}
            sx={{
              borderRadius: borderRadius.md,
              p: 0.5,
              border: 1,
              borderColor: 'primary.main',
              cursor: 'pointer',
              transition: 'all 0.2s',
              '&:hover': {
                transform: 'translateY(-2px)',
                boxShadow: 2,
                borderColor: 'primary.main'
              },
              backgroundColor: 'primary.50',
              minHeight: '64px',
              display: 'flex',
            }}
          >
            <CardContent sx={{
              display: 'flex',
              alignItems: 'center',
              gap: 1.5,
              p: 1.25,
              pb: '8px !important',
              width: '100%'
            }}>
              <Avatar sx={{ bgcolor: 'primary.light', color: 'primary.contrastText', width: 32, height: 32 }}>
                <LabelIcon sx={{ fontSize: '1rem' }} />
              </Avatar>
              <Box flexGrow={1} sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                  <Typography variant="caption" color="text.secondary">Total SKUs</Typography>
                  <Typography variant="h6" sx={{ ml: 1, fontWeight: 'bold' }}>{totalCount}</Typography>
                </Box>
                <Typography variant="caption" color="primary.dark" sx={{ fontSize: '0.7rem', lineHeight: 1 }}>
                  Active references
                </Typography>
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={4} md={4}>
          <Card
            elevation={1}
            sx={{
              borderRadius: borderRadius.md,
              p: 0.5,
              border: 1,
              borderColor: withCategoryCount > 0 ? 'success.main' : 'divider',
              cursor: 'pointer',
              transition: 'all 0.2s',
              '&:hover': {
                transform: 'translateY(-2px)',
                boxShadow: 2,
                borderColor: 'success.main'
              },
              backgroundColor: 'white',
              minHeight: '64px',
              display: 'flex',
            }}
          >
            <CardContent sx={{
              display: 'flex',
              alignItems: 'center',
              gap: 1.5,
              p: 1.25,
              pb: '8px !important',
              width: '100%'
            }}>
              <Avatar sx={{ bgcolor: 'success.light', color: 'success.contrastText', width: 32, height: 32 }}>
                <CategoryIcon sx={{ fontSize: '1rem' }} />
              </Avatar>
              <Box flexGrow={1} sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                  <Typography variant="caption" color="text.secondary">Categorized</Typography>
                  <Typography variant="h6" color="success.main" sx={{ ml: 1, fontWeight: 'bold' }}>{withCategoryCount}</Typography>
                </Box>
                <Typography variant="caption" color="success.dark" sx={{ fontSize: '0.7rem', lineHeight: 1 }}>
                  With categories
                </Typography>
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={4} md={4}>
          <Card
            elevation={1}
            sx={{
              borderRadius: borderRadius.md,
              p: 0.5,
              border: 1,
              borderColor: withPriceCount > 0 ? 'info.main' : 'divider',
              cursor: 'pointer',
              transition: 'all 0.2s',
              '&:hover': {
                transform: 'translateY(-2px)',
                boxShadow: 2,
                borderColor: 'info.main'
              },
              backgroundColor: 'white',
              minHeight: '64px',
              display: 'flex',
            }}
          >
            <CardContent sx={{
              display: 'flex',
              alignItems: 'center',
              gap: 1.5,
              p: 1.25,
              pb: '8px !important',
              width: '100%'
            }}>
              <Avatar sx={{ bgcolor: 'info.light', color: 'info.contrastText', width: 32, height: 32 }}>
                <InventoryIcon sx={{ fontSize: '1rem' }} />
              </Avatar>
              <Box flexGrow={1} sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                  <Typography variant="caption" color="text.secondary">With Prices</Typography>
                  <Typography variant="h6" color="info.main" sx={{ ml: 1, fontWeight: 'bold' }}>{withPriceCount}</Typography>
                </Box>
                <Typography variant="caption" color="info.dark" sx={{ fontSize: '0.7rem', lineHeight: 1 }}>
                  Have pricing data
                </Typography>
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Filters - Regular view on larger screens, drawer on mobile */}
      {!isMobile ? (
        <Paper sx={{ p: 2, mb: 3 }}>
          <Grid container spacing={2} alignItems="center">
            <Grid item xs={12} md={4}>
              <TextField
                fullWidth
                placeholder="Search SKU references..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <SearchIcon color="action" />
                    </InputAdornment>
                  ),
                }}
                size={isMobile ? "small" : "medium"}
              />
            </Grid>
            <Grid item xs={12} md={4}>
              <FormControl fullWidth size={isMobile ? "small" : "medium"}>
                <InputLabel>Category</InputLabel>
                <Select
                  value={categoryFilter}
                  onChange={(e) => setCategoryFilter(e.target.value)}
                  label="Category"
                >
                  <MenuItem value="">All Categories</MenuItem>
                  {categories.map((category) => (
                    <MenuItem key={category.id} value={category.id}>
                      {category.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={4}>
              <FormControl fullWidth size={isMobile ? "small" : "medium"}>
                <InputLabel>Storage Location</InputLabel>
                <Select
                  value={storageFilter}
                  onChange={(e) => setStorageFilter(e.target.value)}
                  label="Storage Location"
                >
                  <MenuItem value="">All Locations</MenuItem>
                  {storageLocations.map((location) => (
                    <MenuItem key={location.id} value={location.id}>
                      {location.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
          </Grid>
        </Paper>
      ) : (
        <Drawer
          anchor="bottom"
          open={filtersOpen}
          onClose={() => setFiltersOpen(false)}
          PaperProps={{
            sx: {
              borderTopLeftRadius: 16,
              borderTopRightRadius: 16,
              pt: 1
            }
          }}
        >
          <Box sx={{ p: 2, pb: 4 }}>
            <Box display="flex" justifyContent="space-between" alignItems="center" mb={2}>
              <Typography variant="h6">Filters</Typography>
              <IconButton onClick={() => setFiltersOpen(false)}>
                <CloseIcon />
              </IconButton>
            </Box>

            <Stack spacing={2}>
              <TextField
                fullWidth
                placeholder="Search SKU references..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                InputProps={{
                  startAdornment: <InputAdornment position="start"><SearchIcon color="action" /></InputAdornment>,
                }}
                size="small"
              />

              <FormControl fullWidth size="small">
                <InputLabel>Category</InputLabel>
                <Select
                  value={categoryFilter}
                  label="Category"
                  onChange={(e) => setCategoryFilter(e.target.value)}
                >
                  <MenuItem value="">All Categories</MenuItem>
                  {categories.map((category) => (
                    <MenuItem key={category.id} value={category.id}>
                      {category.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>

              <FormControl fullWidth size="small">
                <InputLabel>Storage Location</InputLabel>
                <Select
                  value={storageFilter}
                  label="Storage Location"
                  onChange={(e) => setStorageFilter(e.target.value)}
                >
                  <MenuItem value="">All Locations</MenuItem>
                  {storageLocations.map((location) => (
                    <MenuItem key={location.id} value={location.id}>
                      {location.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>

              <Button
                variant="contained"
                onClick={() => setFiltersOpen(false)}
                fullWidth
              >
                Apply Filters
              </Button>
            </Stack>
          </Box>
        </Drawer>
      )}

      {/* Display either List View or Card View based on viewMode state */}
      {viewMode === 'list' ? (
        // List/Table View
        <Paper sx={{ borderRadius: 2, overflow: 'hidden' }}>
          <TableContainer>
            <Table size="small" sx={{ '& .MuiTableCell-root': { px: 2, py: 1.5, whiteSpace: 'nowrap' } }}>
              <TableHead>
                <TableRow>
                  <TableCell width="20%">Name</TableCell>
                  <TableCell width="15%">SKU</TableCell>
                  <TableCell width="12%">Type</TableCell>
                  {!isMobile && <TableCell width="18%">Description</TableCell>}
                  {!isMobile && <TableCell width="10%">Unit</TableCell>}
                  {!isMobile && <TableCell width="10%" align="center">Price</TableCell>}
                  {!isMobile && <TableCell width="10%">Category</TableCell>}
                  <TableCell width="15%" align="right">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {filteredSkuReferences
                  .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                  .map((item) => (
                    <TableRow
                      key={item.id}
                      onClick={() => handleOpenDialog(item)}
                      sx={{
                        cursor: 'pointer',
                        '&:hover': { bgcolor: 'action.hover' },
                      }}
                    >
                      <TableCell>
                        <Box>
                          <Typography variant="subtitle2">
                            {item.name}
                          </Typography>
                          <Typography variant="caption" color="text.secondary">
                            {item.category?.name || 'Uncategorized'}
                          </Typography>
                        </Box>
                      </TableCell>

                      <TableCell>
                        <Chip
                          label={item.sku}
                          variant="outlined"
                          size="small"
                          color="primary"
                        />
                      </TableCell>

                      <TableCell>
                        <Chip
                          label={item.itemType === SkuItemType.RAW_MATERIAL ? 'Raw Material' : 'Finished Product'}
                          variant="outlined"
                          size="small"
                          color={item.itemType === SkuItemType.RAW_MATERIAL ? 'warning' : 'secondary'}
                        />
                      </TableCell>

                      {!isMobile && (
                        <TableCell>
                          <Typography variant="body2" noWrap>
                            {item.description || '-'}
                          </Typography>
                        </TableCell>
                      )}

                      {!isMobile && (
                        <TableCell>
                          <Typography variant="body2">
                            {item.unit || '-'}
                          </Typography>
                        </TableCell>
                      )}

                      {!isMobile && (
                        <TableCell align="center">
                          <Typography variant="body2">
                            {item.unitPrice ? `$${item.unitPrice.toFixed(2)}` : '-'}
                          </Typography>
                        </TableCell>
                      )}

                      {!isMobile && (
                        <TableCell>
                          <Typography variant="body2">
                            {item.category?.name || '-'}
                          </Typography>
                        </TableCell>
                      )}

                      <TableCell align="right">
                        <Box display="flex" gap={0.5} justifyContent="flex-end">
                          <Tooltip title="Check Usage">
                            <IconButton
                              size="small"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleCheckUsage(item);
                              }}
                            >
                              <InfoIcon fontSize="small" />
                            </IconButton>
                          </Tooltip>
                          <Tooltip title="Edit">
                            <IconButton
                              size="small"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleOpenDialog(item);
                              }}
                            >
                              <EditIcon fontSize="small" />
                            </IconButton>
                          </Tooltip>
                          <Tooltip title="Delete">
                            <IconButton
                              size="small"
                              color="error"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleOpenDeleteDialog(item);
                              }}
                            >
                              <DeleteIcon fontSize="small" />
                            </IconButton>
                          </Tooltip>
                        </Box>
                      </TableCell>
                    </TableRow>
                  ))}
              </TableBody>
            </Table>
          </TableContainer>

          <TablePagination
            rowsPerPageOptions={[5, 10, 25, 50]}
            component="div"
            count={filteredSkuReferences.length}
            rowsPerPage={rowsPerPage}
            page={page}
            onPageChange={handleChangePage}
            onRowsPerPageChange={handleChangeRowsPerPage}
          />
        </Paper>
      ) : (
        // Card View
        <Box>
          <Grid container spacing={2}>
            {filteredSkuReferences
              .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
              .map((item) => (
                <Grid item xs={12} sm={6} md={4} key={item.id}>
                  <Card
                    sx={{
                      height: '100%',
                      display: 'flex',
                      flexDirection: 'column',
                      cursor: 'pointer',
                      transition: 'all 0.2s',
                      '&:hover': {
                        transform: 'translateY(-2px)',
                        boxShadow: 3,
                      },
                      borderRadius: borderRadius.md,
                    }}
                    onClick={() => handleOpenDialog(item)}
                  >
                    <CardHeader
                      avatar={
                        <Avatar sx={{ bgcolor: 'primary.main' }}>
                          <LabelIcon />
                        </Avatar>
                      }
                      title={
                        <Typography
                          variant="subtitle1"
                          sx={{
                            fontWeight: 'medium',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            display: '-webkit-box',
                            WebkitLineClamp: 2,
                            WebkitBoxOrient: 'vertical',
                            lineHeight: 1.2,
                            height: 'auto',
                          }}
                        >
                          {item.name}
                        </Typography>
                      }
                      subheader={
                        <Box sx={{ mt: 0.5 }}>
                          <Chip
                            label={item.sku}
                            variant="outlined"
                            size="small"
                            color="primary"
                          />
                        </Box>
                      }
                      action={null}
                      sx={{ pb: 1 }}
                    />

                    <Divider />

                    <CardContent sx={{ pt: 2, pb: 1, flexGrow: 1 }}>
                      <Grid container spacing={2}>
                        <Grid item xs={6}>
                          <Typography variant="subtitle2" color="text.secondary">
                            Unit
                          </Typography>
                          <Typography variant="body1">
                            {item.unit || '-'}
                          </Typography>
                        </Grid>

                        <Grid item xs={6}>
                          <Typography variant="subtitle2" color="text.secondary">
                            Price
                          </Typography>
                          <Typography variant="body1">
                            {item.unitPrice ? `$${item.unitPrice.toFixed(2)}` : '-'}
                          </Typography>
                        </Grid>

                        <Grid item xs={6}>
                          <Typography variant="subtitle2" color="text.secondary">
                            Type
                          </Typography>
                          <Chip
                            label={item.itemType === SkuItemType.RAW_MATERIAL ? 'Raw Material' : 'Finished Product'}
                            variant="outlined"
                            size="small"
                            color={item.itemType === SkuItemType.RAW_MATERIAL ? 'warning' : 'secondary'}
                          />
                        </Grid>

                        <Grid item xs={6}>
                          <Typography variant="subtitle2" color="text.secondary">
                            Category
                          </Typography>
                          <Typography variant="body2">
                            {item.category?.name || 'Uncategorized'}
                          </Typography>
                        </Grid>

                        <Grid item xs={6}>
                          <Typography variant="subtitle2" color="text.secondary">
                            Reorder Level
                          </Typography>
                          <Typography variant="body2">
                            {item.reorderLevel || '-'}
                          </Typography>
                        </Grid>

                        {item.description && (
                          <Grid item xs={12}>
                            <Typography variant="subtitle2" color="text.secondary">
                              Description
                            </Typography>
                            <Typography
                              variant="body2"
                              sx={{
                                overflow: 'hidden',
                                textOverflow: 'ellipsis',
                                display: '-webkit-box',
                                WebkitLineClamp: 2,
                                WebkitBoxOrient: 'vertical',
                              }}
                            >
                              {item.description}
                            </Typography>
                          </Grid>
                        )}
                      </Grid>
                    </CardContent>

                    <CardActions sx={{ justifyContent: 'space-between', pt: 0 }}>
                      <Box>
                        <Tooltip title="Check Usage">
                          <IconButton
                            size="small"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleCheckUsage(item);
                            }}
                          >
                            <InfoIcon fontSize="small" />
                          </IconButton>
                        </Tooltip>
                        <Tooltip title="Edit">
                          <IconButton
                            size="small"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleOpenDialog(item);
                            }}
                          >
                            <EditIcon fontSize="small" />
                          </IconButton>
                        </Tooltip>
                        <Tooltip title="Delete">
                          <IconButton
                            size="small"
                            color="error"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleOpenDeleteDialog(item);
                            }}
                          >
                            <DeleteIcon fontSize="small" />
                          </IconButton>
                        </Tooltip>
                      </Box>
                    </CardActions>
                  </Card>
                </Grid>
              ))}
          </Grid>

          <Box mt={3} display="flex" justifyContent="center">
            <TablePagination
              rowsPerPageOptions={[5, 10, 25, 50]}
              component="div"
              count={filteredSkuReferences.length}
              rowsPerPage={rowsPerPage}
              page={page}
              onPageChange={handleChangePage}
              onRowsPerPageChange={handleChangeRowsPerPage}
            />
          </Box>
        </Box>
      )}

      {/* Create/Edit Dialog */}
      <Dialog
        open={dialogOpen}
        onClose={handleCloseDialog}
        maxWidth="md"
        fullWidth
        fullScreen={isMobile}
      >
        <DialogTitle>
          {editingItem ? 'Edit SKU Reference' : 'Create New SKU Reference'}
        </DialogTitle>
        <DialogContent>
          {error && (
            <Alert severity="error" sx={{ mb: 2 }}>
              {error}
            </Alert>
          )}

          <Grid container spacing={2} sx={{ mt: 1 }}>
            {/* Name - First field */}
            <Grid item xs={12} sm={8}>
              <TextField
                fullWidth
                label="Name *"
                value={formData.name}
                onChange={(e) => handleNameChange(e.target.value)}
                placeholder="Enter product name"
              />
            </Grid>

            {/* Item Type - Second field */}
            <Grid item xs={12} sm={4}>
              <FormControl fullWidth>
                <InputLabel>Item Type *</InputLabel>
                <Select
                  value={formData.itemType}
                  onChange={(e) => setFormData(prev => ({ ...prev, itemType: e.target.value as SkuItemType }))}
                  label="Item Type *"
                >
                  <MenuItem value={SkuItemType.RAW_MATERIAL}>Raw Material</MenuItem>
                  <MenuItem value={SkuItemType.FINISHED_PRODUCT}>Finished Product</MenuItem>
                </Select>
              </FormControl>
            </Grid>

            {/* Category - Second field (used for SKU generation) */}
            <Grid item xs={12} sm={6}>
              <FormControl fullWidth>
                <InputLabel>Category</InputLabel>
                <Select
                  value={formData.categoryId}
                  onChange={(e) => handleCategoryChange(e.target.value)}
                  label="Category"
                >
                  <MenuItem value="">Select Category</MenuItem>
                  {categories.map((category) => (
                    <MenuItem key={category.id} value={category.id}>
                      {category.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            {/* Unit - Third field */}
            <Grid item xs={12} sm={6}>
              <FormControl fullWidth>
                <InputLabel>Unit</InputLabel>
                <Select
                  value={formData.unit}
                  onChange={(e) => setFormData(prev => ({ ...prev, unit: e.target.value }))}
                  label="Unit"
                >
                  <MenuItem value="">Select Unit</MenuItem>
                  {units.map((unit) => (
                    <MenuItem key={unit.id} value={unit.symbol}>
                      {unit.name} ({unit.symbol})
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            {/* Description */}
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Description"
                value={formData.description}
                onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                multiline
                rows={3}
                placeholder="Enter product description"
              />
            </Grid>

            {/* Unit Price */}
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Unit Price"
                value={formData.unitPrice ?? ''}
                onChange={(e) => handleNumericChange('unitPrice', e.target.value)}
                placeholder="0.00"
                InputProps={{
                  sx: {
                    '& input[type=number]': {
                      MozAppearance: 'textfield',
                    },
                    '& input[type=number]::-webkit-outer-spin-button, & input[type=number]::-webkit-inner-spin-button': {
                      WebkitAppearance: 'none',
                      margin: 0,
                    },
                  },
                }}
              />
            </Grid>

            {/* Reorder Level */}
            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label="Reorder Level"
                value={formData.reorderLevel ?? ''}
                onChange={(e) => handleNumericChange('reorderLevel', e.target.value)}
                placeholder="0"
                InputProps={{
                  sx: {
                    '& input[type=number]': {
                      MozAppearance: 'textfield',
                    },
                    '& input[type=number]::-webkit-outer-spin-button, & input[type=number]::-webkit-inner-spin-button': {
                      WebkitAppearance: 'none',
                      margin: 0,
                    },
                  },
                }}
              />
            </Grid>

            {/* Storage Location */}
            <Grid item xs={12}>
              <FormControl fullWidth>
                <InputLabel>Storage Location</InputLabel>
                <Select
                  value={formData.storageLocationId}
                  onChange={(e) => setFormData(prev => ({ ...prev, storageLocationId: e.target.value }))}
                  label="Storage Location"
                >
                  <MenuItem value="">Select Storage Location</MenuItem>
                  {storageLocations.map((location) => (
                    <MenuItem key={location.id} value={location.id}>
                      {location.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            {/* SKU - Last field (auto-generated from above fields) */}
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="SKU *"
                value={formData.sku}
                onChange={(e) => handleSkuChange(e.target.value)}
                placeholder="Auto-generated from name and category"
                helperText={autoGeneratedSku
                  ? "✓ Auto-generated (you can edit if needed)"
                  : "Manual SKU - ensure uniqueness"}
                InputProps={{
                  endAdornment: autoGeneratedSku ? (
                    <Box sx={{ display: 'flex', alignItems: 'center', color: 'success.main', mr: 1 }}>
                      <CheckCircleIcon fontSize="small" />
                    </Box>
                  ) : null
                }}
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>Cancel</Button>
          <Button
            onClick={handleSubmit}
            variant="contained"
            disabled={createMutation.isPending || updateMutation.isPending}
          >
            {createMutation.isPending || updateMutation.isPending ? (
              <CircularProgress size={20} />
            ) : (
              editingItem ? 'Update' : 'Create'
            )}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog
        open={deleteDialogOpen}
        onClose={handleCloseDeleteDialog}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>Confirm Delete</DialogTitle>
        <DialogContent>
          <Typography>
            Are you sure you want to delete the SKU reference "{deletingItem?.name}"?
            This action cannot be undone.
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDeleteDialog}>Cancel</Button>
          <Button
            onClick={handleDelete}
            color="error"
            variant="contained"
            disabled={deleteMutation.isPending}
          >
            {deleteMutation.isPending ? <CircularProgress size={20} /> : 'Delete'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Usage Details Dialog */}
      <Dialog
        open={usageDialogOpen}
        onClose={() => setUsageDialogOpen(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>SKU Usage Details</DialogTitle>
        <DialogContent>
          {usageData && (
            <>
              <Typography variant="h6" gutterBottom>
                Usage Summary
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                Total occurrences: {usageData.usage.totalCount}
              </Typography>

              {usageData.usage.rawMaterials.length > 0 && (
                <Box sx={{ mb: 2 }}>
                  <Typography variant="subtitle2" fontWeight="bold">
                    Raw Materials ({usageData.usage.rawMaterials.length})
                  </Typography>
                  {usageData.usage.rawMaterials.map((item: any) => (
                    <Typography key={item.id} variant="body2">
                      • {item.name} - {item.batchNumber} ({item.quantity} {item.unit})
                    </Typography>
                  ))}
                </Box>
              )}

              {usageData.usage.finishedProducts.length > 0 && (
                <Box sx={{ mt: 2 }}>
                  <Typography variant="subtitle2" fontWeight="bold">
                    Finished Products ({usageData.usage.finishedProducts.length})
                  </Typography>
                  {usageData.usage.finishedProducts.map((item: any) => (
                    <Typography key={item.id} variant="body2">
                      • {item.name} - {item.batchNumber} ({item.quantity} {item.unit})
                    </Typography>
                  ))}
                </Box>
              )}

              {usageData.usage.totalCount === 0 && (
                <Alert severity="info" sx={{ mt: 2 }}>
                  This SKU reference is not currently in use.
                </Alert>
              )}
            </>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setUsageDialogOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>

      {/* Snackbar */}
      <Snackbar
        open={snackbar.open}
        autoHideDuration={6000}
        onClose={() => setSnackbar({ ...snackbar, open: false })}
      >
        <Alert
          onClose={() => setSnackbar({ ...snackbar, open: false })}
          severity={snackbar.severity}
          sx={{ width: '100%' }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Container>
  );
};

export default SkuReferencePage;
